server:
  port: 7070

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/vladimirqt233/Sistema-Venta-Libreria.git
          search-paths: config-data
          default-label: main
          clone-on-start: true

  security:
    user:
      name: ${CONFIG_SERVER_USER:admin123}
      password: ${CONFIG_SERVER_PASSWORD:admin123}