server:
  port: 7071

spring:
  application:
    name: config-server
  profiles:
    active: native

  cloud:
    config:
      server:
        native:
          search-locations: file:../config-data,file:./config-data

  security:
    user:
      name: ${CONFIG_SERVER_USER:root}
      password: ${CONFIG_SERVER_PASSWORD:123456}
