spring:
  application:
    name: ms-registry-service
  profiles:
    active: development
  config:
    import: optional:configserver:http://${CONFIG_SERVER_USER:root}:${CONFIG_SERVER_PASSWORD:123456}@localhost:7071
