spring:
  application:
    name: ms-auth-service

  profiles:
    active: development

  config:
    import: "optional:configserver:http://${CONFIG_SERVER_USER:root}:${CONFIG_SERVER_PASSWORD}@localhost:7070"

  datasource:
    url: jdbc:mysql://localhost:3306/ms_auth
    username: ${DB_USERNAME:admin123}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true