spring:
  application:
    name: ms-cliente-service

  profiles:
    active: development

  config:
    import: "optional:configserver:http://${CONFIG_SERVER_USER:root}:${CONFIG_SERVER_PASSWORD:123456}@localhost:7071"

  datasource:
    url: jdbc:mysql://localhost:3306/ms_cliente?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
